---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: src/main
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: src/main/go
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: src/test/acceptance-tests/jira-indexer
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: src/test/acceptance-tests/jira-runtime
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: src/util/code-analyzer
    schedule:
      interval: weekly
